environment:
  nodejs_version: "lts"
  RUSTUP_USE_REQWEST: 1
  CARGO_HTTP_CHECK_REVOKE: false
install:
  - ps: Install-Product node $env:nodejs_version
  - appveyor-retry appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init.exe -y
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustup target add wasm32-unknown-unknown
  - rustc -V
  - cargo -V
  - node -v

build: false

test_script:
  - cargo build --verbose
  - cargo build --verbose --release --examples
  - ps: |
      node -e "require('./target/wasm32-unknown-unknown/release/wap.js').wap('target/wasm32-unknown-unknown/release/examples/hello_node.wasm')" > out.txt
      $R = $LastExitCode
      Get-Content out.txt
      $OUT = Get-Content out.txt
      Remove-Item –path out.txt
      if ($R -ne 0) { $host.SetShouldExit($R)  }
      if ($OUT -ne [array]"Hello World") { $host.SetShouldExit(1) }
  - ps: |
      node -e "require('./target/wasm32-unknown-unknown/release/wap.js').wap('target/wasm32-unknown-unknown/release/examples/test_node.wasm')" > out.txt
      $R = $LastExitCode
      Get-Content out.txt
      $OUT = Get-Content out.txt
      Remove-Item –path out.txt
      if ($R -ne 0) { $host.SetShouldExit($R)  }
      if ($OUT -ne [array]"Tests Complete. (Finally shutdown)") { $host.SetShouldExit(1) }
